# Docker Compose para una pila WooCommerce de alto rendimiento
# Basado en las recomendaciones de la investigación: Nginx, PHP-FPM, MariaDB, y Redis.

version: '3.8'

services:
  # Servicio de Base de Datos: MariaDB
  # MariaDB es una bifurcación de MySQL recomendada y de alto rendimiento.[1, 2]
  db:
    image: mariadb:10.11 # Usando una versión LTS recomendada.[1]
    container_name: woo_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'tu_password_root_muy_seguro' # ¡CAMBIAR ESTO!
      MYSQL_DATABASE: 'woocommerce_db'
      MYSQL_USER: 'woo_user'
      MYSQL_PASSWORD: 'tu_password_db_seguro' # ¡CAMBIAR ESTO!
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - woo-network
    healthcheck:
      # CORRECCIÓN: Se añadió el comando de test para verificar si MariaDB está listo.
      test: "mysql -u woo_user -P 3306 -p'tu_password_db_seguro' woocommerce_db -Bse 'SELECT 1'"
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de Caché de Objetos: Redis
  # Redis es la opción superior para el caché de objetos persistente en WooCommerce.[3, 4]
  redis:
    image: redis:7-alpine
    container_name: woo_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - woo-network
    healthcheck:
      # CORRECCIÓN: Se añadió el comando de test para verificar si Redis está respondiendo.
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de Aplicación: WordPress con PHP-FPM
  # Usamos la imagen FPM para que Nginx pueda actuar como proxy inverso.
  # Se recomienda la última versión de PHP para rendimiento y seguridad.[1, 2]
  wordpress:
    image: wordpress:php8.3-fpm-alpine
    container_name: woo_wordpress
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: 'woo_user'
      WORDPRESS_DB_PASSWORD: 'tu_password_db_seguro' # ¡CAMBIAR ESTO!
      WORDPRESS_DB_NAME: 'woocommerce_db'
      # Variables para el plugin Redis Object Cache
      WP_REDIS_HOST: 'redis'
      WP_REDIS_PORT: '6379'
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - woo-network

  # Servidor Web: Nginx
  # Nginx es superior a Apache para manejar alta concurrencia y servir archivos estáticos.[5, 6]
  nginx:
    image: nginx:stable-alpine
    container_name: woo_nginx
    restart: unless-stopped
    ports:
      - "7575:80" # Puerto modificado a 7575
      - "443:443" # Descomentar y configurar SSL para producción
    volumes:
      - wordpress_data:/var/www/html:ro # Montar como solo lectura
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # -./ssl:/etc/nginx/ssl:ro # Descomentar para producción con certificados SSL
    depends_on:
      - wordpress
    networks:
      - woo-network

# Volúmenes para persistencia de datos
volumes:
  db_data:
  redis_data:
  wordpress_data:

# Red para la comunicación entre contenedores
networks:
  woo-network:
    driver: bridge