version: '3.8'

services:
  # Servicio de Base de Datos: MariaDB
  db:
    image: mariadb:10.11
    restart: unless-stopped
    command: --innodb-buffer-pool-size=1G --max-connections=150
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - woo-internal
    healthcheck:
      test: "mysql -u ${DB_USER} -P 3306 -p${DB_PASSWORD} ${DB_NAME} -Bse 'SELECT 1'"
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de Caché de Objetos: Redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - woo-internal
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de Aplicación: WordPress con PHP-FPM
  wordpress:
    image: wordpress:php8.3-fpm-alpine
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_NAME}'
      # Inyección automática en wp-config.php (Redis y HTTPS Proxy)
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', 6379 );
        define( 'WP_REDIS_DATABASE', 0 );
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($$_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
            $$_SERVER['HTTPS'] = 'on';
        }
    volumes:
      - wordpress_data:/var/www/html
      - ./php-conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    networks:
      - woo-internal

  # Servidor Web: Nginx Interno
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST} # Detectado por el Proxy Maestro
    # ports:
    #   - "80:80"
    volumes:
      - wordpress_data:/var/www/html:ro # Montar como solo lectura
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress
    networks:
      - woo-internal
      - proxy-network

# Volúmenes para persistencia de datos de esta instancia
volumes:
  db_data:
  redis_data:
  wordpress_data:

    # Redes
networks:
  woo-internal:
    driver: bridge # Red privada de esta tienda
  proxy-network:
    external: true
    name: nginx-proxy # Red compartida con el proxy frontal maestro
